<?php

namespace Mateffy\Magic;

enum FeatureType: string
{
    case AccessControl = 'access-control';
    case AcousticCeiling = 'acoustic-ceiling';
    case Address = 'address';
    case AirConditioning = 'air-conditioning';
    case Balcony = 'balcony';
    case Bees = 'bees';
    case BikeSlots = 'bike-slots';
    case BlockHeating = 'block-heating';
    case CCTV = 'cctv';
    case Cantina = 'cantina';
    case CarpetFlooring = 'carpet-flooring';
    case Carsharing = 'carsharing';
    case CentralFireAlarmSystem = 'central-fire-alarm-system';
    case CentralFireAlarmSystemFireDepartment = 'central-fire-alarm-system-fire-department';
    case CentralHeating = 'central-heating';
    case CeramicFacade = 'ceramic-facade';
    case CleaningService = 'cleaning-service';
    case CloseToPublicTransport = 'close-to-public-transport';
    case CompletelyRenovated = 'completely-renovated';
    case CooledHalls = 'cooled-halls';
    case Cooling = 'cooling';
    case Custom = 'custom';
    case DeliveryFor24Hours = 'delivery-for-24h';
    case DistanceAirport = 'distance-airport';
    case DistanceMainStation = 'distance-main-station';
    case DistancePort = 'distance-port';
    case DistrictHeating = 'district-heating';
    case DoubleFloor = 'double-floor';
    case DressingRoom = 'dressing-room';
    case ElectricHeating = 'electric-heating';
    case ElectricVehicleChargingStation = 'electric-vehicle-charging-station';
    case ElectronicLock = 'electronic-lock';
    case Elevators = 'elevators';
    case FiberglassConnection = 'fiberglass-connection';
    case FloorHeating = 'floor-heating';
    case FlooredWindows = 'floored-windows';
    case Floors = 'floors';
    case GasHeating = 'gas-heating';
    case GastronomyOnSite = 'gastronomy-on-site';
    case GeoThermal = 'geo-thermal';
    case GreenCourtyard = 'green-courtyard';
    case GreenLeaseContracts = 'green-lease-contracts';
    case GreenedFacade = 'greened-facade';
    case GreenedRoof = 'greened-roof';
    case GroundLevelAccess = 'ground-level-access';
    case Guarded = 'guarded';
    case HandicapAccessible = 'handicap-accessible';
    case HandicapFullyAccessible = 'handicap-fully-accessible';
    case HardwoodFlooring = 'hardwood-flooring';
    case HeatPump = 'heat-pump';
    case HeatedHalls = 'heated-halls';
    case HeavyDutyCrane = 'heavy-duty-crane';
    case HeavyDutyElevator = 'heavy-duty-elevator';
    case HighCeilings = 'high-ceilings';
    case HighVoltageOutlet = 'high-voltage-outlet';
    case HydraulicLift = 'hydraulic-lift';
    case IndividuallyExpandable = 'individually-expandable';
    case InfraredHeating = 'infrared-heating';
    case Kindergarden = 'kindergarden';
    case Kitchen = 'kitchen';
    case LKWSlots = 'lkw-slots';
    case LaboratoryS1 = 'laboratory-s1';
    case LaboratoryS2 = 'laboratory-s2';
    case LedLighting = 'led-lighting';
    case LightingWithMotionDetection = 'lighting-with-motion-detection';
    case MarketingWebsite = 'marketing-website';
    case MaxFloorLoad = 'max-floor-load';
    case MaximumSurfaceDesealing = 'maximum-surface-desealing';
    case MeetingRooms = 'meeting-rooms';
    case Modernized = 'modernized';
    case MonumentProtection = 'monument-protection';
    case NearbySports = 'nearby-sports';
    case NeedsRenovation = 'needs-renovation';
    case NestingBox = 'nesting-box';
    case NewConstruction = 'new-construction';
    case NumberOfRooms = 'number-of-rooms';
    case NumberOfWorkplaces = 'number-of-workplaces';
    case OpenRooms = 'open-rooms';
    case OutdoorSunshade = 'outdoor-sunshade';
    case OutdoorSunshadeElectric = 'outdoor-sunshade-electric';
    case PKWSlots = 'pkw-slots';
    case ParkingGarage = 'parking-garage';
    case PlacesForSocializing = 'places-for-socializing';
    case PlotArea = 'plot-area';
    case RampAccess = 'ramp-access';
    case Recepionist = 'receptionist';
    case Recycling = 'recycling';
    case RentableArea = 'rentable-area';
    case RepresentativeFoyer = 'representative-foyer';
    case Revitalized = 'revitalized';
    case RollingGates = 'rolling-gates';
    case RoofTerrace = 'roof-terrace';
    case ServerRoom = 'server-room';
    case Shower = 'shower';
    case SmartMetering = 'smart-metering';
    case SocialTenant = 'social-tenant';
    case SolarEnergy = 'solar-energy';
    case SolarHeating = 'solar-heating';
    case SprinklerSystem = 'sprinkler-system';
    case StorageRack = 'storage-rack';
    case StoreyHeating = 'storey-heating';
    case TeeKitchen = 'tee-kitchen';
    case ThinkTanks = 'think-tanks';
    case UrbanGardening = 'urban-gardening';
    case VariableRoomDivision = 'variable-room-division';
    case Ventilation = 'ventilation';
    case WashingClothes = 'washing-clothes';
    case WaterRetention = 'water-retention';
    case WildFlowerGrasses = 'wild-flower-grasses';
    case WindEnergy = 'wind-energy';
    case WiredWithCat7 = 'wired-with-cat7';
    case WoodHybridConstruction = 'wood-hybrid-construction';
    case WoodenFacade = 'wooden-façade';
    case YearOfConstruction = 'year-of-construction';
    case YearOfRenovation = 'year-of-renovation';

    public function label(): string
    {
        return match ($this) {
            self::AccessControl => 'Zugangskontrolle',
            self::AcousticCeiling => 'Akustikdecke',
            self::Address => 'Adresse',
            self::AirConditioning => 'Klimatisierung',
            self::Balcony => 'Balkon',
            self::Bees => 'Bienenvölker',
            self::BikeSlots => 'Fahrradstellplätze',
            self::BlockHeating => 'Blockheizkraftwerk',
            self::CCTV => 'Video-Überwachung',
            self::Cantina => 'Kantine',
            self::CarpetFlooring => 'Teppichboden',
            self::Carsharing => 'Carsharing',
            self::CentralFireAlarmSystem => 'BMA-Zentrale',
            self::CentralFireAlarmSystemFireDepartment => 'BMA-Zentrale + Feuerwehr',
            self::CentralHeating => 'Zentralheizung',
            self::CeramicFacade => 'Keramikfassade',
            self::CleaningService => 'Reinigungsdienst',
            self::CloseToPublicTransport => 'ÖPNV direkt vor der Tür',
            self::CompletelyRenovated => 'Kernsaniert',
            self::CooledHalls => 'Gekühlte Hallen',
            self::Cooling => 'Kühlung',
            self::Custom => 'Benutzerdefiniert',
            self::DeliveryFor24Hours => '24h Andienung',
            self::DistanceAirport => 'Distanz Flughafen',
            self::DistanceMainStation => 'Distanz Hauptbahnhof',
            self::DistancePort => 'Distanz Hafen',
            self::DistrictHeating => 'Fernwärme',
            self::DoubleFloor => 'Doppelbodentrassen',
            self::DressingRoom => 'Umkleideraum',
            self::ElectricHeating => 'Elektroheizung',
            self::ElectricVehicleChargingStation => 'E-Ladestation',
            self::ElectronicLock => 'Elektronische Schließanlage',
            self::Elevators => 'Personenaufzüge',
            self::FiberglassConnection => 'Glasfaseranschluss',
            self::FloorHeating => 'Fußbodenheizung',
            self::FlooredWindows => 'Bodentiefe Fenster',
            self::Floors => 'Etagen',
            self::GasHeating => 'Gasheizung',
            self::GastronomyOnSite => 'Gastronomie auf dem Gelände',
            self::GeoThermal => 'Geothermie',
            self::GreenCourtyard => 'Grüner Innenhof',
            self::GreenLeaseContracts => 'Green Lease Mietverträge',
            self::GreenedFacade => 'Begrünte Fassade',
            self::GreenedRoof => 'Begrünte Dachfläche',
            self::GroundLevelAccess => 'Ebenerdige Andienung',
            self::Guarded => 'Pförtner',
            self::HandicapAccessible => 'Barrierearm',
            self::HandicapFullyAccessible => 'Barrierefrei',
            self::HardwoodFlooring => 'Parkettboden',
            self::HeatPump => 'Wärmepumpe',
            self::HeatedHalls => 'Beheizte Hallen',
            self::HeavyDutyCrane => 'Schwerlastkran',
            self::HeavyDutyElevator => 'Lastenaufzüge',
            self::HighCeilings => 'Hohe Decken',
            self::HighVoltageOutlet => 'Starkstromanschluss',
            self::HydraulicLift => 'Hydraulische Hebebühne',
            self::IndividuallyExpandable => 'Individuell ausbaubar',
            self::InfraredHeating => 'Infrarot Heizung',
            self::Kindergarden => 'Kita auf der Liegenschaft',
            self::Kitchen => 'Küche',
            self::LKWSlots => 'LKW-Stellplätze',
            self::LaboratoryS1 => 'S1 Labor',
            self::LaboratoryS2 => 'S2 Labor',
            self::LedLighting => 'LED-Beleuchtung',
            self::LightingWithMotionDetection => 'Beleuchtung mit Bewegungsmelder',
            self::MarketingWebsite => 'Webseite',
            self::MaxFloorLoad => 'Hohe Bodentraglast',
            self::MaximumSurfaceDesealing => 'Maximale Flächenentsieglung',
            self::MeetingRooms => 'Meetingräume',
            self::Modernized => 'Modernisiert',
            self::MonumentProtection => 'Denkmalschutz',
            self::NearbySports => 'Sportangebot in der Nähe',
            self::NeedsRenovation => 'Renovierung nötig',
            self::NestingBox => 'Nistkästen',
            self::NewConstruction => 'Neubau',
            self::NumberOfRooms => 'Anzahl der Zimmer',
            self::NumberOfWorkplaces => 'Arbeitsplätze',
            self::OpenRooms => 'offene Raumstruktur',
            self::OutdoorSunshade => 'Sonnenschutz',
            self::OutdoorSunshadeElectric => 'Elektrischer Sonnenschutz',
            self::PKWSlots => 'PKW-Stellplätze',
            self::ParkingGarage => 'Parkhaus/Tiefgarage',
            self::PlacesForSocializing => 'Orte für sozialen Austausch',
            self::PlotArea => 'Grundstücksfläche',
            self::RampAccess => 'Rampen-Andienung',
            self::Recepionist => 'Besetzter Empfang',
            self::Recycling => 'Recycling Konzept',
            self::RentableArea => 'Gesamtmietfläche',
            self::RepresentativeFoyer => 'Repräsentatives Foyer',
            self::Revitalized => 'Revitalisiert',
            self::RollingGates => 'Sektional- & Rolltore',
            self::RoofTerrace => 'Dachterrasse',
            self::ServerRoom => 'Serverraum',
            self::Shower => 'Duschen',
            self::SmartMetering => 'Smart Metering',
            self::SocialTenant => 'Soziale Mieter',
            self::SolarEnergy => 'Photovoltaikanlage',
            self::SolarHeating => 'Solarthermie',
            self::SprinklerSystem => 'Sprinkleranlage',
            self::StorageRack => 'Hochregallager',
            self::StoreyHeating => 'Etagenheizung',
            self::TeeKitchen => 'Teeküche',
            self::ThinkTanks => 'Think Tanks',
            self::UrbanGardening => 'Urban Gardening',
            self::VariableRoomDivision => 'Variable Raumaufteilung',
            self::Ventilation => 'Lüftung',
            self::WashingClothes => 'Textilreinigung',
            self::WaterRetention => 'Regenrückhaltebecken',
            self::WildFlowerGrasses => 'Wildblumenwiese',
            self::WindEnergy => 'Windenergie',
            self::WiredWithCat7 => 'CAT7-Verkabelung',
            self::WoodHybridConstruction => 'Holzhybridbauweise',
            self::WoodenFacade => 'Holzfassade',
            self::YearOfConstruction => 'Baujahr',
            self::YearOfRenovation => 'Renoviert',
        };
    }
}
